site_name: IT Journal Constantin
repo_url: https://github.com/constantin-koenig/ITjournal
theme:
  name: material
  features: 
    - navigation.tabs
    - navigation.instant
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences


